name: 'Setup MVST mobile CI'
description: 'Sets up tools on MVST runner'
inputs:
  node-version:
    description: 'Node version'
    default: 16
  java-version:
    description: 'Java version'
    default: '11'
  java-dist:
    description: 'Java distribution'
    default: 'zulu'
  flutter-version:
    description: 'Flutter version'
    default: '3.3.7'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-dist }}
        java-version: ${{ inputs.java-version }}
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: 'stable'
    - run: yarn --version || npm install -g yarn
      shell: bash
